# Name of your application. Used to uniquely configure containers.
service: sticker_app

# Name of the container image.
image: sticker_app

# Deploy to these servers.
servers:
  web:
    - 192.168.1.101

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: false
  hosts:
    - stickers.vandelden.family
  forward_headers: true
  # Proxy connects to your container on port 80 by default.
  app_port: 3000
  healthcheck:
    path: /up
    interval: 2
    timeout: 2

# Credentials for your image host.
registry:
  server: registry.vandelden.family
  username: root

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://root@192.168.1.102
  local: false
  context: "."
  # Pass in additional build args needed for your Dockerfile.
  args:
    RUBY_VERSION: <%= File.read('.ruby-version').strip.delete_prefix('ruby-') %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    APP_NAME: StickerApp
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    # When you start using multiple servers, you should split out job processing to a dedicated machine.
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - SECRET_KEY_BASE

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
  apps: server exec docker exec kamal-proxy kamal-proxy list

# Use a persistent storage volume for sqlite database files and local Active Storage files.
volumes:
  - "/home/app_storage/sticker_app/storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

deploy_timeout: 20
